version: "3"
services:
  redis-server:
    image: "redis:alpine"
  node-app:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    extra_hosts:
      - "mongoservice:172.17.0.1"
      - host.docker.internal:host-gateway
    volumes:
      - /app/node_modules
      - ./:/app
